#This file describes GitHub action that builds releases when a tag v* is pushed, e.g. v0.0.2
#It's build based on:
#1. https://github.com/firebelley/godot-export
#2. https://bitbra.in/2020/08/01/publish-godot-game-to-itchio.html
#To test github actions locally you can use https://github.com/nektos/act
#with docker installed

on:
  push:
    tags:
      - 'v*'

jobs:
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Export game to Github
    steps:
      # Always include the checkout step so that
      # your project is available for Godot to export
      - name: checkout
        uses: actions/checkout@v3.0.2
        # Ensure that you get the entire project history
        with:
          fetch-depth: 0
      - name: get tag from version
        id: tag_version
        run: |
          echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}
      - name: install 7z #Install wine to be able to add icon to win executable
        id: install_7z
        run: |
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y p7zip-full
      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      # - name: install wine #Install wine to be able to add icon to win executable
      #   id: wine_install
      #   run: |
      #     sudo apt install wine64
      #     echo ::set-output name=WINE_PATH::$(which wine64)
      - name: create game release
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v3.0.0
        with:
          # Defining all the required inputs
          # I used the mono version of Godot in this example
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_linux_headless.64.zip
          # godot_executable_download_url: http://192.168.1.4:8000/Godot_v3.4.4-stable_linux_headless.64.zip #used for local debig
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_export_templates.tpz
          # set this either to . or your game path, e.g. ./godot in case
          # your game is within a sub-directory
          relative_project_path: ./game
          # read the wine path here that was an output of the wine_install step
          # wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'